#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODEL_PATH = ROOT / "db" / "model" / "phase2_schema.json"
MIGRATION_PATH = ROOT / "src" / "main" / "resources" / "db" / "migration" / "V3__phase2_generated_modules.sql"
DOC_PATH = ROOT / "docs" / "generated" / "phase2_schema_generated.md"

COMMON_COLUMNS = [
    "id UUID PRIMARY KEY DEFAULT gen_random_uuid()",
    "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP",
    "updated_at TIMESTAMP",
    "version BIGINT NOT NULL DEFAULT 0",
    "deleted BOOLEAN NOT NULL DEFAULT FALSE"
]


def column_sql(col):
    parts = [f"{col['name']} {col['type']}"]
    if not col.get("nullable", True):
        parts.append("NOT NULL")
    if "default" in col:
        parts.append(f"DEFAULT {col['default']}")
    if col.get("unique"):
        parts.append("UNIQUE")
    if "references" in col:
        parts.append(f"REFERENCES {col['references']}")
    return " ".join(parts)


def generate_sql(model):
    lines = [
        "-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.",
        "-- Generated by scripts/generate_db_artifacts.py from db/model/phase2_schema.json",
        ""
    ]

    for table in model["tables"]:
        lines.append(f"CREATE TABLE {table['name']} (")

        defs = []
        if table.get("tenantScoped", False):
            defs.append("tenant_id UUID NOT NULL REFERENCES tenant (id)")

        for col in table["columns"]:
            defs.append(column_sql(col))

        defs.extend(COMMON_COLUMNS)

        for idx, definition in enumerate(defs):
            suffix = "," if idx < len(defs) - 1 else ""
            lines.append(f"    {definition}{suffix}")
        lines.append(");")
        lines.append("")

        for index in table.get("indexes", []):
            cols = ", ".join(index["columns"])
            lines.append(f"CREATE INDEX {index['name']} ON {table['name']} ({cols});")
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def generate_doc(model):
    lines = [
        "# Phase-2 Generated Schema",
        "",
        "This file is generated from `db/model/phase2_schema.json`.",
        "",
        "## Tables"
    ]

    for table in model["tables"]:
        lines.append(f"### `{table['name']}`")
        lines.append("")
        if table.get("tenantScoped", False):
            lines.append("- Tenant-scoped: `true`")
        lines.append("- Columns:")
        for col in table["columns"]:
            nullable = "NULL" if col.get("nullable", True) else "NOT NULL"
            details = f"`{col['name']}` `{col['type']}` {nullable}"
            if "references" in col:
                details += f" references `{col['references']}`"
            if col.get("unique"):
                details += " unique"
            if "default" in col:
                details += f" default `{col['default']}`"
            lines.append(f"  - {details}")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def main():
    model = json.loads(MODEL_PATH.read_text())
    MIGRATION_PATH.write_text(generate_sql(model))
    DOC_PATH.write_text(generate_doc(model))
    print(f"Generated {MIGRATION_PATH}")
    print(f"Generated {DOC_PATH}")


if __name__ == "__main__":
    main()
