#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MODEL_PATH = ROOT / "db" / "model" / "phase2_schema.json"
DEFAULT_MIGRATION_PATH = ROOT / "src" / "main" / "resources" / "db" / "migration" / "V3__phase2_generated_modules.sql"
DEFAULT_DOC_PATH = ROOT / "docs" / "generated" / "phase2_schema_generated.md"

COMMON_COLUMNS = [
    "id UUID PRIMARY KEY DEFAULT gen_random_uuid()",
    "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP",
    "updated_at TIMESTAMP",
    "version BIGINT NOT NULL DEFAULT 0",
    "deleted BOOLEAN NOT NULL DEFAULT FALSE"
]


def column_sql(col):
    parts = [f"{col['name']} {col['type']}"]
    if not col.get("nullable", True):
        parts.append("NOT NULL")
    if "default" in col:
        parts.append(f"DEFAULT {col['default']}")
    if col.get("unique"):
        parts.append("UNIQUE")
    if "references" in col:
        parts.append(f"REFERENCES {col['references']}")
    return " ".join(parts)


def rel_path(path):
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path.resolve())


def generate_sql(model, model_path):
    lines = [
        "-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.",
        f"-- Generated by scripts/generate_db_artifacts.py from {rel_path(model_path)}",
        ""
    ]

    for table in model["tables"]:
        lines.append(f"CREATE TABLE {table['name']} (")

        defs = []
        if table.get("tenantScoped", False):
            defs.append("tenant_id UUID NOT NULL REFERENCES tenant (id)")

        for col in table["columns"]:
            defs.append(column_sql(col))

        defs.extend(COMMON_COLUMNS)

        for idx, definition in enumerate(defs):
            suffix = "," if idx < len(defs) - 1 else ""
            lines.append(f"    {definition}{suffix}")
        lines.append(");")
        lines.append("")

        for index in table.get("indexes", []):
            cols = ", ".join(index["columns"])
            lines.append(f"CREATE INDEX {index['name']} ON {table['name']} ({cols});")
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def generate_doc(model, model_path):
    lines = [
        "# Generated Schema",
        "",
        f"This file is generated from `{rel_path(model_path)}`.",
        "",
        "## Tables"
    ]

    for table in model["tables"]:
        lines.append(f"### `{table['name']}`")
        lines.append("")
        if table.get("tenantScoped", False):
            lines.append("- Tenant-scoped: `true`")
        lines.append("- Columns:")
        for col in table["columns"]:
            nullable = "NULL" if col.get("nullable", True) else "NOT NULL"
            details = f"`{col['name']}` `{col['type']}` {nullable}"
            if "references" in col:
                details += f" references `{col['references']}`"
            if col.get("unique"):
                details += " unique"
            if "default" in col:
                details += f" default `{col['default']}`"
            lines.append(f"  - {details}")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def parse_args():
    parser = argparse.ArgumentParser(description="Generate Flyway SQL + docs from JSON table model")
    parser.add_argument("--model", default=str(DEFAULT_MODEL_PATH), help="Path to JSON model file")
    parser.add_argument("--migration", default=str(DEFAULT_MIGRATION_PATH), help="Output SQL migration path")
    parser.add_argument("--doc", default=str(DEFAULT_DOC_PATH), help="Output markdown doc path")
    return parser.parse_args()


def main():
    args = parse_args()
    model_path = Path(args.model).resolve()
    migration_path = Path(args.migration).resolve()
    doc_path = Path(args.doc).resolve()

    model = json.loads(model_path.read_text())
    migration_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.parent.mkdir(parents=True, exist_ok=True)

    migration_path.write_text(generate_sql(model, model_path))
    doc_path.write_text(generate_doc(model, model_path))
    print(f"Generated {migration_path}")
    print(f"Generated {doc_path}")


if __name__ == "__main__":
    main()
