-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase10_schema.json

CREATE TABLE app_role (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    system_role BOOLEAN NOT NULL DEFAULT FALSE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_app_role_tenant ON app_role (tenant_id);
CREATE INDEX idx_app_role_code ON app_role (tenant_id, code);

CREATE TABLE permission (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    code VARCHAR(100) NOT NULL,
    module_name VARCHAR(60),
    description VARCHAR(500),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_permission_tenant ON permission (tenant_id);
CREATE INDEX idx_permission_code ON permission (tenant_id, code);

CREATE TABLE role_permission (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    role_id UUID NOT NULL REFERENCES app_role(id),
    permission_id UUID NOT NULL REFERENCES permission(id),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_role_permission_tenant ON role_permission (tenant_id);
CREATE INDEX idx_role_permission_role ON role_permission (tenant_id, role_id);
CREATE INDEX idx_role_permission_permission ON role_permission (tenant_id, permission_id);

CREATE TABLE user_additional_role (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    user_id UUID NOT NULL REFERENCES users(id),
    role_id UUID NOT NULL REFERENCES app_role(id),
    granted_by UUID REFERENCES users(id),
    granted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_user_additional_role_tenant ON user_additional_role (tenant_id);
CREATE INDEX idx_user_additional_role_user ON user_additional_role (tenant_id, user_id);
CREATE INDEX idx_user_additional_role_role ON user_additional_role (tenant_id, role_id);
