-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase11_schema.json

CREATE TABLE billing_cycle (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    cycle_name VARCHAR(100) NOT NULL,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    due_date DATE NOT NULL,
    late_fee_applicable_date DATE,
    status VARCHAR(30) NOT NULL,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_billing_cycle_tenant ON billing_cycle (tenant_id);
CREATE INDEX idx_billing_cycle_year_month ON billing_cycle (tenant_id, year, month);
CREATE INDEX idx_billing_cycle_status ON billing_cycle (tenant_id, status);

CREATE TABLE maintenance_charge (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    unit_id UUID NOT NULL REFERENCES unit(id),
    billing_cycle_id UUID NOT NULL REFERENCES billing_cycle(id),
    base_amount NUMERIC(12, 2),
    calculation_method VARCHAR(50),
    area_based_amount NUMERIC(12, 2),
    fixed_amount NUMERIC(12, 2),
    total_amount NUMERIC(12, 2) NOT NULL,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_maintenance_charge_tenant ON maintenance_charge (tenant_id);
CREATE INDEX idx_maintenance_charge_cycle ON maintenance_charge (tenant_id, billing_cycle_id);
CREATE INDEX idx_maintenance_charge_unit ON maintenance_charge (tenant_id, unit_id);

CREATE TABLE special_assessment (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    assessment_name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    total_amount NUMERIC(12, 2) NOT NULL,
    per_unit_amount NUMERIC(12, 2),
    assessment_date DATE,
    due_date DATE NOT NULL,
    created_by UUID REFERENCES users(id),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_special_assessment_tenant ON special_assessment (tenant_id);
CREATE INDEX idx_special_assessment_due ON special_assessment (tenant_id, due_date);
CREATE INDEX idx_special_assessment_status ON special_assessment (tenant_id, status);

CREATE TABLE invoice (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    invoice_number VARCHAR(100) NOT NULL UNIQUE,
    unit_id UUID NOT NULL REFERENCES unit(id),
    billing_cycle_id UUID REFERENCES billing_cycle(id),
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    late_fee NUMERIC(12, 2) NOT NULL DEFAULT 0,
    gst_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    other_charges NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12, 2) NOT NULL,
    outstanding_amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_invoice_tenant ON invoice (tenant_id);
CREATE INDEX idx_invoice_unit ON invoice (tenant_id, unit_id);
CREATE INDEX idx_invoice_cycle ON invoice (tenant_id, billing_cycle_id);
CREATE INDEX idx_invoice_status ON invoice (tenant_id, status);

CREATE TABLE payment_reminder (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    invoice_id UUID NOT NULL REFERENCES invoice(id),
    reminder_type VARCHAR(50) NOT NULL,
    sent_at TIMESTAMP,
    channel VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_payment_reminder_tenant ON payment_reminder (tenant_id);
CREATE INDEX idx_payment_reminder_invoice ON payment_reminder (tenant_id, invoice_id);
CREATE INDEX idx_payment_reminder_status ON payment_reminder (tenant_id, status);

CREATE TABLE late_fee_rule (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    rule_name VARCHAR(100) NOT NULL,
    days_after_due INTEGER NOT NULL,
    fee_type VARCHAR(30) NOT NULL,
    fee_amount NUMERIC(12, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_late_fee_rule_tenant ON late_fee_rule (tenant_id);
CREATE INDEX idx_late_fee_rule_active ON late_fee_rule (tenant_id, active);
