-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase12_schema.json

CREATE TABLE account_head (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    head_name VARCHAR(100) NOT NULL,
    head_type VARCHAR(50) NOT NULL,
    parent_head_id UUID REFERENCES account_head(id),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_account_head_tenant ON account_head (tenant_id);
CREATE INDEX idx_account_head_type ON account_head (tenant_id, head_type);
CREATE INDEX idx_account_head_parent ON account_head (tenant_id, parent_head_id);

CREATE TABLE fund_category (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    category_name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    current_balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_fund_category_tenant ON fund_category (tenant_id);
CREATE INDEX idx_fund_category_name ON fund_category (tenant_id, category_name);

CREATE TABLE vendor (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    vendor_name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(100),
    phone VARCHAR(20),
    email VARCHAR(255),
    address VARCHAR(1000),
    gstin VARCHAR(50),
    pan VARCHAR(50),
    vendor_type VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_vendor_tenant ON vendor (tenant_id);
CREATE INDEX idx_vendor_type ON vendor (tenant_id, vendor_type);
CREATE INDEX idx_vendor_active ON vendor (tenant_id, active);

CREATE TABLE expense (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    expense_number VARCHAR(100) NOT NULL UNIQUE,
    account_head_id UUID NOT NULL REFERENCES account_head(id),
    fund_category_id UUID REFERENCES fund_category(id),
    vendor_id UUID REFERENCES vendor(id),
    expense_date DATE NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    description VARCHAR(1000),
    invoice_number VARCHAR(100),
    invoice_url VARCHAR(1000),
    payment_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    approved_by UUID REFERENCES users(id),
    approval_date DATE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_expense_tenant ON expense (tenant_id);
CREATE INDEX idx_expense_vendor ON expense (tenant_id, vendor_id);
CREATE INDEX idx_expense_account_head ON expense (tenant_id, account_head_id);
CREATE INDEX idx_expense_status ON expense (tenant_id, payment_status);
CREATE INDEX idx_expense_date ON expense (tenant_id, expense_date);

CREATE TABLE vendor_payment (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    vendor_id UUID NOT NULL REFERENCES vendor(id),
    expense_id UUID REFERENCES expense(id),
    payment_date DATE NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(50),
    transaction_reference VARCHAR(255),
    created_by UUID REFERENCES users(id),
    status VARCHAR(50) NOT NULL DEFAULT 'COMPLETED',
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_vendor_payment_tenant ON vendor_payment (tenant_id);
CREATE INDEX idx_vendor_payment_vendor ON vendor_payment (tenant_id, vendor_id);
CREATE INDEX idx_vendor_payment_expense ON vendor_payment (tenant_id, expense_id);
CREATE INDEX idx_vendor_payment_status ON vendor_payment (tenant_id, status);

CREATE TABLE budget (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    financial_year VARCHAR(20) NOT NULL,
    account_head_id UUID NOT NULL REFERENCES account_head(id),
    budgeted_amount NUMERIC(12, 2) NOT NULL,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_budget_tenant ON budget (tenant_id);
CREATE INDEX idx_budget_financial_year ON budget (tenant_id, financial_year);
CREATE INDEX idx_budget_account_head ON budget (tenant_id, account_head_id);
