-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase13_schema.json

CREATE TABLE visitor (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    visitor_name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    vehicle_number VARCHAR(50),
    visitor_type VARCHAR(50),
    id_proof_type VARCHAR(50),
    id_proof_number VARCHAR(100),
    photo_url VARCHAR(1000),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_visitor_registry_tenant ON visitor (tenant_id);
CREATE INDEX idx_visitor_registry_phone ON visitor (tenant_id, phone);
CREATE INDEX idx_visitor_registry_type ON visitor (tenant_id, visitor_type);

CREATE TABLE visitor_entry_exit_log (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    visitor_pass_id UUID NOT NULL REFERENCES visitor_pass(id),
    entry_time TIMESTAMP,
    exit_time TIMESTAMP,
    entry_gate VARCHAR(50),
    exit_gate VARCHAR(50),
    security_guard_entry UUID REFERENCES users(id),
    security_guard_exit UUID REFERENCES users(id),
    face_capture_url VARCHAR(1000),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_visitor_log_tenant ON visitor_entry_exit_log (tenant_id);
CREATE INDEX idx_visitor_log_pass ON visitor_entry_exit_log (tenant_id, visitor_pass_id);
CREATE INDEX idx_visitor_log_entry_time ON visitor_entry_exit_log (tenant_id, entry_time);
CREATE INDEX idx_visitor_log_exit_time ON visitor_entry_exit_log (tenant_id, exit_time);

CREATE TABLE domestic_help_registry (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    help_name VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    help_type VARCHAR(50),
    permanent_pass BOOLEAN NOT NULL DEFAULT FALSE,
    police_verification_done BOOLEAN NOT NULL DEFAULT FALSE,
    verification_date DATE,
    photo_url VARCHAR(1000),
    registered_by UUID REFERENCES users(id),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_domestic_help_tenant ON domestic_help_registry (tenant_id);
CREATE INDEX idx_domestic_help_type ON domestic_help_registry (tenant_id, help_type);
CREATE INDEX idx_domestic_help_phone ON domestic_help_registry (tenant_id, phone);

CREATE TABLE domestic_help_unit_mapping (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    domestic_help_id UUID NOT NULL REFERENCES domestic_help_registry(id),
    unit_id UUID NOT NULL REFERENCES unit(id),
    start_date DATE,
    end_date DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_domestic_help_unit_tenant ON domestic_help_unit_mapping (tenant_id);
CREATE INDEX idx_domestic_help_unit_help ON domestic_help_unit_mapping (tenant_id, domestic_help_id);
CREATE INDEX idx_domestic_help_unit_unit ON domestic_help_unit_mapping (tenant_id, unit_id);
CREATE INDEX idx_domestic_help_unit_active ON domestic_help_unit_mapping (tenant_id, active);

CREATE TABLE blacklist (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    person_name VARCHAR(255),
    phone VARCHAR(20),
    reason VARCHAR(1000),
    blacklisted_by UUID REFERENCES users(id),
    blacklist_date DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_blacklist_tenant ON blacklist (tenant_id);
CREATE INDEX idx_blacklist_phone ON blacklist (tenant_id, phone);
CREATE INDEX idx_blacklist_active ON blacklist (tenant_id, active);

CREATE TABLE delivery_log (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    unit_id UUID NOT NULL REFERENCES unit(id),
    delivery_partner VARCHAR(100) NOT NULL,
    tracking_number VARCHAR(100),
    delivery_time TIMESTAMP NOT NULL,
    received_by UUID REFERENCES users(id),
    security_guard_id UUID REFERENCES users(id),
    photo_url VARCHAR(1000),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_delivery_log_tenant ON delivery_log (tenant_id);
CREATE INDEX idx_delivery_log_unit ON delivery_log (tenant_id, unit_id);
CREATE INDEX idx_delivery_log_partner ON delivery_log (tenant_id, delivery_partner);
CREATE INDEX idx_delivery_log_time ON delivery_log (tenant_id, delivery_time);
