-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase14_schema.json

CREATE TABLE asset_category (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    category_name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_asset_category_tenant ON asset_category (tenant_id);
CREATE INDEX idx_asset_category_name ON asset_category (tenant_id, category_name);

CREATE TABLE complaint_comment (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    complaint_id UUID NOT NULL REFERENCES complaint(id),
    user_id UUID NOT NULL REFERENCES users(id),
    comment VARCHAR(2000) NOT NULL,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_complaint_comment_tenant ON complaint_comment (tenant_id);
CREATE INDEX idx_complaint_comment_complaint ON complaint_comment (tenant_id, complaint_id);
CREATE INDEX idx_complaint_comment_user ON complaint_comment (tenant_id, user_id);

CREATE TABLE work_order (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    work_order_number VARCHAR(100) NOT NULL UNIQUE,
    complaint_id UUID NOT NULL REFERENCES complaint(id),
    asset_id UUID REFERENCES asset(id),
    vendor_id UUID REFERENCES vendor(id),
    work_description VARCHAR(2000) NOT NULL,
    estimated_cost NUMERIC(12,2),
    actual_cost NUMERIC(12,2),
    scheduled_date DATE,
    completion_date DATE,
    status VARCHAR(40) NOT NULL,
    created_by UUID REFERENCES users(id),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_work_order_tenant ON work_order (tenant_id);
CREATE INDEX idx_work_order_complaint ON work_order (tenant_id, complaint_id);
CREATE INDEX idx_work_order_vendor ON work_order (tenant_id, vendor_id);
CREATE INDEX idx_work_order_status ON work_order (tenant_id, status);

CREATE TABLE preventive_maintenance_schedule (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    asset_id UUID NOT NULL REFERENCES asset(id),
    maintenance_type VARCHAR(120) NOT NULL,
    frequency VARCHAR(40) NOT NULL,
    last_maintenance_date DATE,
    next_maintenance_date DATE NOT NULL,
    assigned_vendor_id UUID REFERENCES vendor(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_preventive_maintenance_tenant ON preventive_maintenance_schedule (tenant_id);
CREATE INDEX idx_preventive_maintenance_asset ON preventive_maintenance_schedule (tenant_id, asset_id);
CREATE INDEX idx_preventive_maintenance_due ON preventive_maintenance_schedule (tenant_id, next_maintenance_date);
CREATE INDEX idx_preventive_maintenance_active ON preventive_maintenance_schedule (tenant_id, active);

CREATE TABLE asset_depreciation (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    asset_id UUID NOT NULL REFERENCES asset(id),
    depreciation_method VARCHAR(40) NOT NULL,
    depreciation_rate NUMERIC(6,2) NOT NULL,
    depreciation_year INTEGER NOT NULL,
    depreciation_amount NUMERIC(12,2) NOT NULL,
    book_value NUMERIC(12,2) NOT NULL,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_asset_depreciation_tenant ON asset_depreciation (tenant_id);
CREATE INDEX idx_asset_depreciation_asset ON asset_depreciation (tenant_id, asset_id);
CREATE INDEX idx_asset_depreciation_year ON asset_depreciation (tenant_id, depreciation_year);
