-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase15_schema.json

CREATE TABLE amenity_time_slot (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    amenity_id UUID NOT NULL REFERENCES amenity(id),
    slot_name VARCHAR(100) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_amenity_time_slot_tenant ON amenity_time_slot (tenant_id);
CREATE INDEX idx_amenity_time_slot_amenity ON amenity_time_slot (tenant_id, amenity_id);
CREATE INDEX idx_amenity_time_slot_active ON amenity_time_slot (tenant_id, active);

CREATE TABLE amenity_pricing (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    amenity_id UUID NOT NULL REFERENCES amenity(id),
    time_slot_id UUID NOT NULL REFERENCES amenity_time_slot(id),
    day_type VARCHAR(50) NOT NULL,
    base_price NUMERIC(12,2) NOT NULL,
    peak_hour BOOLEAN NOT NULL DEFAULT FALSE,
    peak_hour_multiplier NUMERIC(5,2),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_amenity_pricing_tenant ON amenity_pricing (tenant_id);
CREATE INDEX idx_amenity_pricing_amenity ON amenity_pricing (tenant_id, amenity_id);
CREATE INDEX idx_amenity_pricing_slot ON amenity_pricing (tenant_id, time_slot_id);

CREATE TABLE amenity_booking_rule (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    amenity_id UUID NOT NULL REFERENCES amenity(id),
    rule_type VARCHAR(100) NOT NULL,
    rule_value VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_amenity_booking_rule_tenant ON amenity_booking_rule (tenant_id);
CREATE INDEX idx_amenity_booking_rule_amenity ON amenity_booking_rule (tenant_id, amenity_id);

CREATE TABLE amenity_cancellation_policy (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    amenity_id UUID NOT NULL REFERENCES amenity(id),
    days_before_booking INTEGER NOT NULL,
    refund_percentage NUMERIC(6,2) NOT NULL,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_amenity_cancel_policy_tenant ON amenity_cancellation_policy (tenant_id);
CREATE INDEX idx_amenity_cancel_policy_amenity ON amenity_cancellation_policy (tenant_id, amenity_id);

CREATE TABLE meeting_agenda (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    meeting_id UUID NOT NULL REFERENCES meeting(id),
    agenda_item VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    display_order INTEGER NOT NULL,
    presenter UUID REFERENCES users(id),
    estimated_duration INTEGER,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_meeting_agenda_tenant ON meeting_agenda (tenant_id);
CREATE INDEX idx_meeting_agenda_meeting ON meeting_agenda (tenant_id, meeting_id);

CREATE TABLE meeting_attendee (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    meeting_id UUID NOT NULL REFERENCES meeting(id),
    user_id UUID NOT NULL REFERENCES users(id),
    invitation_sent_at TIMESTAMP,
    rsvp_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    attendance_status VARCHAR(50),
    joined_at TIMESTAMP,
    left_at TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_meeting_attendee_tenant ON meeting_attendee (tenant_id);
CREATE INDEX idx_meeting_attendee_meeting ON meeting_attendee (tenant_id, meeting_id);
CREATE INDEX idx_meeting_attendee_user ON meeting_attendee (tenant_id, user_id);

CREATE TABLE meeting_minutes_record (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    meeting_id UUID NOT NULL REFERENCES meeting(id),
    minutes_content TEXT NOT NULL,
    summary VARCHAR(4000),
    ai_generated_summary VARCHAR(4000),
    prepared_by UUID REFERENCES users(id),
    approved_by UUID REFERENCES users(id),
    approval_date DATE,
    document_url VARCHAR(1000),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_meeting_minutes_tenant ON meeting_minutes_record (tenant_id);
CREATE INDEX idx_meeting_minutes_meeting ON meeting_minutes_record (tenant_id, meeting_id);

CREATE TABLE meeting_resolution (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    meeting_id UUID NOT NULL REFERENCES meeting(id),
    resolution_number VARCHAR(100) NOT NULL,
    resolution_text TEXT NOT NULL,
    proposed_by UUID REFERENCES users(id),
    seconded_by UUID REFERENCES users(id),
    status VARCHAR(50) NOT NULL,
    votes_for INTEGER NOT NULL DEFAULT 0,
    votes_against INTEGER NOT NULL DEFAULT 0,
    votes_abstain INTEGER NOT NULL DEFAULT 0,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_meeting_resolution_tenant ON meeting_resolution (tenant_id);
CREATE INDEX idx_meeting_resolution_meeting ON meeting_resolution (tenant_id, meeting_id);
CREATE INDEX idx_meeting_resolution_status ON meeting_resolution (tenant_id, status);

CREATE TABLE meeting_vote (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    resolution_id UUID NOT NULL REFERENCES meeting_resolution(id),
    user_id UUID NOT NULL REFERENCES users(id),
    vote VARCHAR(30) NOT NULL,
    voted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_meeting_vote_tenant ON meeting_vote (tenant_id);
CREATE INDEX idx_meeting_vote_resolution ON meeting_vote (tenant_id, resolution_id);
CREATE INDEX idx_meeting_vote_user ON meeting_vote (tenant_id, user_id);

CREATE TABLE meeting_action_item (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    meeting_id UUID NOT NULL REFERENCES meeting(id),
    action_description VARCHAR(2000) NOT NULL,
    assigned_to UUID REFERENCES users(id),
    due_date DATE,
    priority VARCHAR(20),
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    completion_date DATE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_meeting_action_item_tenant ON meeting_action_item (tenant_id);
CREATE INDEX idx_meeting_action_item_meeting ON meeting_action_item (tenant_id, meeting_id);
CREATE INDEX idx_meeting_action_item_assigned ON meeting_action_item (tenant_id, assigned_to);
CREATE INDEX idx_meeting_action_item_status ON meeting_action_item (tenant_id, status);

CREATE TABLE meeting_reminder (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    meeting_id UUID NOT NULL REFERENCES meeting(id),
    reminder_type VARCHAR(50) NOT NULL,
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_meeting_reminder_tenant ON meeting_reminder (tenant_id);
CREATE INDEX idx_meeting_reminder_meeting ON meeting_reminder (tenant_id, meeting_id);
