-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase16_schema.json

CREATE TABLE staff_leave (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    staff_id UUID NOT NULL REFERENCES staff(id),
    leave_type VARCHAR(50) NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    number_of_days INTEGER NOT NULL,
    reason VARCHAR(2000),
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    approved_by UUID REFERENCES users(id),
    approval_date DATE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_staff_leave_tenant ON staff_leave (tenant_id);
CREATE INDEX idx_staff_leave_staff ON staff_leave (tenant_id, staff_id);
CREATE INDEX idx_staff_leave_status ON staff_leave (tenant_id, status);
CREATE INDEX idx_staff_leave_dates ON staff_leave (tenant_id, from_date, to_date);

CREATE TABLE payroll_component (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    component_name VARCHAR(100) NOT NULL,
    component_type VARCHAR(50) NOT NULL,
    taxable BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_payroll_component_tenant ON payroll_component (tenant_id);
CREATE INDEX idx_payroll_component_name ON payroll_component (tenant_id, component_name);
CREATE INDEX idx_payroll_component_type ON payroll_component (tenant_id, component_type);

CREATE TABLE staff_salary_structure (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    staff_id UUID NOT NULL REFERENCES staff(id),
    payroll_component_id UUID NOT NULL REFERENCES payroll_component(id),
    amount NUMERIC(12,2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NOT NULL,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_staff_salary_structure_tenant ON staff_salary_structure (tenant_id);
CREATE INDEX idx_staff_salary_structure_staff ON staff_salary_structure (tenant_id, staff_id);
CREATE INDEX idx_staff_salary_structure_component ON staff_salary_structure (tenant_id, payroll_component_id);
CREATE INDEX idx_staff_salary_structure_active ON staff_salary_structure (tenant_id, active);

CREATE TABLE payroll_detail (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    payroll_id UUID NOT NULL REFERENCES payroll(id),
    payroll_component_id UUID NOT NULL REFERENCES payroll_component(id),
    amount NUMERIC(12,2) NOT NULL,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_payroll_detail_tenant ON payroll_detail (tenant_id);
CREATE INDEX idx_payroll_detail_payroll ON payroll_detail (tenant_id, payroll_id);
CREATE INDEX idx_payroll_detail_component ON payroll_detail (tenant_id, payroll_component_id);
