-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase17_schema.json

CREATE TABLE helpdesk_ticket_attachment (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    ticket_id UUID NOT NULL REFERENCES helpdesk_ticket(id),
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(2000) NOT NULL,
    uploaded_by UUID REFERENCES users(id),
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_helpdesk_ticket_attachment_tenant ON helpdesk_ticket_attachment (tenant_id);
CREATE INDEX idx_helpdesk_ticket_attachment_ticket ON helpdesk_ticket_attachment (tenant_id, ticket_id);

CREATE TABLE fire_drill_record (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    drill_date DATE NOT NULL,
    drill_time TIME,
    conducted_by UUID REFERENCES users(id),
    evacuation_time INTEGER,
    participants_count INTEGER,
    observations VARCHAR(2000),
    report_url VARCHAR(2000),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_fire_drill_record_tenant ON fire_drill_record (tenant_id);
CREATE INDEX idx_fire_drill_record_date ON fire_drill_record (tenant_id, drill_date);

CREATE TABLE safety_equipment (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    equipment_type VARCHAR(100) NOT NULL,
    equipment_tag VARCHAR(100),
    location VARCHAR(255),
    installation_date DATE,
    last_inspection_date DATE,
    next_inspection_date DATE,
    inspection_frequency_days INTEGER,
    functional BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_safety_equipment_tenant ON safety_equipment (tenant_id);
CREATE INDEX idx_safety_equipment_type ON safety_equipment (tenant_id, equipment_type);
CREATE INDEX idx_safety_equipment_next_inspection ON safety_equipment (tenant_id, next_inspection_date);

CREATE TABLE safety_inspection (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    equipment_id UUID NOT NULL REFERENCES safety_equipment(id),
    inspection_date DATE NOT NULL,
    inspected_by UUID REFERENCES users(id),
    inspection_result VARCHAR(50) NOT NULL,
    remarks VARCHAR(2000),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_safety_inspection_tenant ON safety_inspection (tenant_id);
CREATE INDEX idx_safety_inspection_equipment ON safety_inspection (tenant_id, equipment_id);
CREATE INDEX idx_safety_inspection_date ON safety_inspection (tenant_id, inspection_date);

CREATE TABLE document_access_log (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    document_id UUID NOT NULL REFERENCES document(id),
    accessed_by UUID REFERENCES users(id),
    access_type VARCHAR(50) NOT NULL,
    accessed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_document_access_log_tenant ON document_access_log (tenant_id);
CREATE INDEX idx_document_access_log_document ON document_access_log (tenant_id, document_id);
CREATE INDEX idx_document_access_log_user ON document_access_log (tenant_id, accessed_by);
CREATE INDEX idx_document_access_log_time ON document_access_log (tenant_id, accessed_at);
