-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase18_schema.json

CREATE TABLE diesel_generator (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    generator_name VARCHAR(100) NOT NULL,
    capacity_kva NUMERIC(10, 2) NOT NULL,
    location VARCHAR(255),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_diesel_generator_tenant ON diesel_generator (tenant_id);
CREATE INDEX idx_diesel_generator_name ON diesel_generator (tenant_id, generator_name);

CREATE TABLE generator_log (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    generator_id UUID NOT NULL REFERENCES diesel_generator(id),
    log_date DATE NOT NULL,
    start_time TIMESTAMP,
    stop_time TIMESTAMP,
    runtime_hours NUMERIC(5, 2),
    diesel_consumed NUMERIC(10, 2),
    diesel_cost NUMERIC(10, 2),
    meter_reading_before NUMERIC(10, 2),
    meter_reading_after NUMERIC(10, 2),
    units_generated NUMERIC(10, 2),
    operator_id UUID REFERENCES users(id),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_generator_log_tenant ON generator_log (tenant_id);
CREATE INDEX idx_generator_log_generator_date ON generator_log (tenant_id, generator_id, log_date);
CREATE INDEX idx_generator_log_date ON generator_log (tenant_id, log_date);

CREATE TABLE carpool_listing (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    posted_by UUID REFERENCES users(id),
    route_from VARCHAR(255) NOT NULL,
    route_to VARCHAR(255) NOT NULL,
    departure_time TIME NOT NULL,
    available_seats INTEGER NOT NULL,
    days_of_week VARCHAR(100) NOT NULL,
    vehicle_type VARCHAR(50),
    contact_preference VARCHAR(50),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_carpool_listing_tenant ON carpool_listing (tenant_id);
CREATE INDEX idx_carpool_listing_posted_by ON carpool_listing (tenant_id, posted_by);
CREATE INDEX idx_carpool_listing_route ON carpool_listing (tenant_id, route_from, route_to);
