-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase19_schema.json

CREATE TABLE announcement_read_receipt (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    announcement_id UUID NOT NULL REFERENCES announcement(id),
    user_id UUID NOT NULL REFERENCES users(id),
    read_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_ann_read_receipt_tenant ON announcement_read_receipt (tenant_id);
CREATE INDEX idx_ann_read_receipt_announcement ON announcement_read_receipt (tenant_id, announcement_id);
CREATE INDEX idx_ann_read_receipt_user ON announcement_read_receipt (tenant_id, user_id);
