-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase20_schema.json

CREATE TABLE unit_ownership_history (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    unit_id UUID NOT NULL REFERENCES unit(id),
    previous_ownership_status VARCHAR(20) NOT NULL,
    new_ownership_status VARCHAR(20) NOT NULL,
    changed_by UUID REFERENCES users(id),
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes VARCHAR(500),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_unit_ownership_history_tenant ON unit_ownership_history (tenant_id);
CREATE INDEX idx_unit_ownership_history_unit ON unit_ownership_history (tenant_id, unit_id);
CREATE INDEX idx_unit_ownership_history_changed_at ON unit_ownership_history (tenant_id, changed_at);
