-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase2_schema.json

CREATE TABLE helpdesk_category (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sla_hours INTEGER,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_helpdesk_category_tenant ON helpdesk_category (tenant_id);

CREATE TABLE helpdesk_ticket (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    ticket_number VARCHAR(100) NOT NULL UNIQUE,
    category_id UUID REFERENCES helpdesk_category(id),
    raised_by UUID REFERENCES users(id),
    unit_id UUID,
    subject VARCHAR(255) NOT NULL,
    description TEXT,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(50) NOT NULL,
    assigned_to UUID REFERENCES users(id),
    assigned_at TIMESTAMP,
    resolved_at TIMESTAMP,
    resolution_notes VARCHAR(2000),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_helpdesk_ticket_tenant ON helpdesk_ticket (tenant_id);
CREATE INDEX idx_helpdesk_ticket_status ON helpdesk_ticket (tenant_id, status);
CREATE INDEX idx_helpdesk_ticket_assigned ON helpdesk_ticket (tenant_id, assigned_to);

CREATE TABLE helpdesk_comment (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    ticket_id UUID NOT NULL REFERENCES helpdesk_ticket(id),
    user_id UUID REFERENCES users(id),
    comment VARCHAR(2000) NOT NULL,
    internal_note BOOLEAN NOT NULL DEFAULT FALSE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_helpdesk_comment_tenant ON helpdesk_comment (tenant_id);
CREATE INDEX idx_helpdesk_comment_ticket ON helpdesk_comment (ticket_id);

CREATE TABLE emergency_contact (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    contact_type VARCHAR(100) NOT NULL,
    contact_name VARCHAR(255) NOT NULL,
    phone_primary VARCHAR(20) NOT NULL,
    phone_secondary VARCHAR(20),
    address VARCHAR(500),
    display_order INTEGER,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_emergency_contact_tenant ON emergency_contact (tenant_id);

CREATE TABLE sos_alert (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    alert_number VARCHAR(100) NOT NULL UNIQUE,
    raised_by UUID REFERENCES users(id),
    unit_id UUID,
    alert_type VARCHAR(100) NOT NULL,
    location VARCHAR(255),
    description VARCHAR(2000),
    latitude NUMERIC(10, 8),
    longitude NUMERIC(11, 8),
    status VARCHAR(50) NOT NULL,
    responded_by UUID REFERENCES users(id),
    responded_at TIMESTAMP,
    resolved_at TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_sos_alert_tenant ON sos_alert (tenant_id);
CREATE INDEX idx_sos_alert_status ON sos_alert (tenant_id, status);

CREATE TABLE document_category (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    category_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    parent_category_id UUID REFERENCES document_category(id),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_document_category_tenant ON document_category (tenant_id);

CREATE TABLE document (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    document_name VARCHAR(255) NOT NULL,
    category_id UUID REFERENCES document_category(id),
    document_type VARCHAR(50) NOT NULL,
    file_url VARCHAR(2000) NOT NULL,
    file_size BIGINT,
    description VARCHAR(1000),
    version_label VARCHAR(50),
    public_access BOOLEAN NOT NULL DEFAULT FALSE,
    uploaded_by UUID REFERENCES users(id),
    upload_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiry_date DATE,
    tags VARCHAR(500),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_document_tenant ON document (tenant_id);
CREATE INDEX idx_document_category ON document (tenant_id, category_id);
