-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase3_schema.json

CREATE TABLE staff (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    employee_id VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    phone VARCHAR(20),
    email VARCHAR(255),
    designation VARCHAR(100) NOT NULL,
    date_of_joining DATE NOT NULL,
    date_of_leaving DATE,
    employment_type VARCHAR(50) NOT NULL,
    basic_salary NUMERIC(10, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_staff_tenant ON staff (tenant_id);
CREATE INDEX idx_staff_active ON staff (tenant_id, active);

CREATE TABLE staff_attendance (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    staff_id UUID NOT NULL REFERENCES staff(id),
    attendance_date DATE NOT NULL,
    check_in_time TIMESTAMP,
    check_out_time TIMESTAMP,
    status VARCHAR(50) NOT NULL,
    marked_by UUID REFERENCES users(id),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_staff_attendance_tenant ON staff_attendance (tenant_id);
CREATE INDEX idx_staff_attendance_staff_date ON staff_attendance (staff_id, attendance_date);

CREATE TABLE payroll (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    staff_id UUID NOT NULL REFERENCES staff(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    working_days INTEGER NOT NULL,
    present_days INTEGER NOT NULL,
    gross_salary NUMERIC(10, 2) NOT NULL,
    total_deductions NUMERIC(10, 2) NOT NULL DEFAULT 0,
    net_salary NUMERIC(10, 2) NOT NULL,
    payment_date DATE,
    payment_method VARCHAR(50),
    payment_reference VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    payslip_url VARCHAR(2000),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_payroll_tenant ON payroll (tenant_id);
CREATE INDEX idx_payroll_staff_period ON payroll (staff_id, year, month);

CREATE TABLE water_tank (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    tank_name VARCHAR(100) NOT NULL,
    tank_type VARCHAR(50) NOT NULL,
    capacity NUMERIC(10, 2) NOT NULL,
    location VARCHAR(255),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_water_tank_tenant ON water_tank (tenant_id);

CREATE TABLE water_level_log (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    tank_id UUID NOT NULL REFERENCES water_tank(id),
    reading_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    level_percentage NUMERIC(5, 2) NOT NULL,
    volume NUMERIC(10, 2),
    recorded_by UUID REFERENCES users(id),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_water_level_log_tenant ON water_level_log (tenant_id);
CREATE INDEX idx_water_level_log_tank_time ON water_level_log (tank_id, reading_time);

CREATE TABLE electricity_meter (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    meter_number VARCHAR(100) NOT NULL UNIQUE,
    meter_type VARCHAR(50) NOT NULL,
    location VARCHAR(255),
    unit_id UUID,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_electricity_meter_tenant ON electricity_meter (tenant_id);

CREATE TABLE electricity_reading (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    meter_id UUID NOT NULL REFERENCES electricity_meter(id),
    reading_date DATE NOT NULL,
    reading_value NUMERIC(10, 2) NOT NULL,
    units_consumed NUMERIC(10, 2),
    cost NUMERIC(10, 2),
    recorded_by UUID REFERENCES users(id),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_electricity_reading_tenant ON electricity_reading (tenant_id);
CREATE INDEX idx_electricity_reading_meter_date ON electricity_reading (meter_id, reading_date);

CREATE TABLE marketplace_category (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    category_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_marketplace_category_tenant ON marketplace_category (tenant_id);

CREATE TABLE marketplace_listing (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    listing_number VARCHAR(100) NOT NULL UNIQUE,
    category_id UUID REFERENCES marketplace_category(id),
    listing_type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price NUMERIC(10, 2),
    negotiable BOOLEAN NOT NULL DEFAULT FALSE,
    images VARCHAR(2000),
    posted_by UUID REFERENCES users(id),
    unit_id UUID,
    status VARCHAR(50) NOT NULL,
    views_count INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_marketplace_listing_tenant ON marketplace_listing (tenant_id);
CREATE INDEX idx_marketplace_listing_status ON marketplace_listing (tenant_id, status);
CREATE INDEX idx_marketplace_listing_posted_by ON marketplace_listing (tenant_id, posted_by);

CREATE TABLE marketplace_inquiry (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    listing_id UUID NOT NULL REFERENCES marketplace_listing(id),
    inquired_by UUID REFERENCES users(id),
    message VARCHAR(2000),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_marketplace_inquiry_tenant ON marketplace_inquiry (tenant_id);
CREATE INDEX idx_marketplace_inquiry_listing ON marketplace_inquiry (listing_id);
