-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase4_schema.json

CREATE TABLE report_template (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    template_name VARCHAR(255) NOT NULL,
    report_type VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    query_template TEXT,
    parameters_json TEXT,
    created_by UUID REFERENCES users(id),
    system_template BOOLEAN NOT NULL DEFAULT FALSE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_report_template_tenant ON report_template (tenant_id);
CREATE INDEX idx_report_template_type ON report_template (tenant_id, report_type);

CREATE TABLE scheduled_report (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    template_id UUID NOT NULL REFERENCES report_template(id),
    report_name VARCHAR(255) NOT NULL,
    frequency VARCHAR(50) NOT NULL,
    recipients VARCHAR(2000),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_generated_at TIMESTAMP,
    next_generation_at TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_scheduled_report_tenant ON scheduled_report (tenant_id);
CREATE INDEX idx_scheduled_report_active ON scheduled_report (tenant_id, active);

CREATE TABLE analytics_dashboard (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    dashboard_name VARCHAR(255) NOT NULL,
    dashboard_type VARCHAR(100) NOT NULL,
    widgets_json TEXT,
    created_by UUID REFERENCES users(id),
    default_dashboard BOOLEAN NOT NULL DEFAULT FALSE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_analytics_dashboard_tenant ON analytics_dashboard (tenant_id);
CREATE INDEX idx_analytics_dashboard_type ON analytics_dashboard (tenant_id, dashboard_type);
CREATE INDEX idx_analytics_dashboard_default ON analytics_dashboard (tenant_id, default_dashboard);
