-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase5_schema.json

CREATE TABLE system_log (
    tenant_id UUID REFERENCES tenant(id),
    user_id UUID REFERENCES users(id),
    log_level VARCHAR(20) NOT NULL,
    logger_name VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    exception_trace TEXT,
    endpoint VARCHAR(255),
    correlation_id VARCHAR(100),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_system_log_tenant ON system_log (tenant_id);
CREATE INDEX idx_system_log_level ON system_log (log_level);
CREATE INDEX idx_system_log_created_at ON system_log (created_at);

CREATE TABLE api_request_log (
    request_id VARCHAR(100),
    tenant_id UUID REFERENCES tenant(id),
    user_id UUID REFERENCES users(id),
    endpoint VARCHAR(255) NOT NULL,
    http_method VARCHAR(10) NOT NULL,
    request_body TEXT,
    response_status INTEGER NOT NULL,
    response_time_ms BIGINT NOT NULL,
    ip_address VARCHAR(50),
    user_agent VARCHAR(1000),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_api_request_log_tenant ON api_request_log (tenant_id);
CREATE INDEX idx_api_request_log_user ON api_request_log (user_id);
CREATE INDEX idx_api_request_log_status ON api_request_log (response_status);
CREATE INDEX idx_api_request_log_endpoint ON api_request_log (endpoint);
CREATE INDEX idx_api_request_log_created_at ON api_request_log (created_at);
