-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase6_schema.json

CREATE TABLE tenant_config (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    config_key VARCHAR(100) NOT NULL,
    config_value TEXT,
    category VARCHAR(50),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_tenant_config_tenant ON tenant_config (tenant_id);
CREATE INDEX idx_tenant_config_key ON tenant_config (tenant_id, config_key);
CREATE INDEX idx_tenant_config_category ON tenant_config (tenant_id, category);

CREATE TABLE system_setting (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    setting_key VARCHAR(120) NOT NULL,
    setting_value TEXT,
    setting_group VARCHAR(80),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_system_setting_tenant ON system_setting (tenant_id);
CREATE INDEX idx_system_setting_key ON system_setting (tenant_id, setting_key);
CREATE INDEX idx_system_setting_group ON system_setting (tenant_id, setting_group);

CREATE TABLE stored_file (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    file_id VARCHAR(120) NOT NULL UNIQUE,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(150),
    file_size BIGINT NOT NULL,
    storage_path VARCHAR(2000) NOT NULL,
    uploaded_by UUID REFERENCES users(id),
    checksum VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    expires_at TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_stored_file_tenant ON stored_file (tenant_id);
CREATE INDEX idx_stored_file_uploaded_by ON stored_file (tenant_id, uploaded_by);
CREATE INDEX idx_stored_file_status ON stored_file (tenant_id, status);
