-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase7_schema.json

CREATE TABLE payment_gateway_txn (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    transaction_ref VARCHAR(120) NOT NULL UNIQUE,
    bill_id UUID NOT NULL REFERENCES maintenance_bill(id),
    provider VARCHAR(50) NOT NULL DEFAULT 'MANUAL_SIMULATOR',
    gateway_order_id VARCHAR(120),
    gateway_payment_id VARCHAR(120),
    amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'INR',
    mode VARCHAR(50) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    callback_payload TEXT,
    failure_reason VARCHAR(500),
    initiated_by UUID REFERENCES users(id),
    verified_by UUID REFERENCES users(id),
    verified_at TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_payment_gateway_txn_tenant ON payment_gateway_txn (tenant_id);
CREATE INDEX idx_payment_gateway_txn_bill ON payment_gateway_txn (tenant_id, bill_id);
CREATE INDEX idx_payment_gateway_txn_status ON payment_gateway_txn (tenant_id, status);
CREATE INDEX idx_payment_gateway_txn_provider ON payment_gateway_txn (tenant_id, provider);
