-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by scripts/generate_db_artifacts.py from db/model/phase8_schema.json

CREATE TABLE auth_token (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    user_id UUID NOT NULL REFERENCES users(id),
    token_value VARCHAR(128) NOT NULL UNIQUE,
    token_type VARCHAR(40) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP,
    metadata VARCHAR(500),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_auth_token_tenant ON auth_token (tenant_id);
CREATE INDEX idx_auth_token_user_type ON auth_token (tenant_id, user_id, token_type);
CREATE INDEX idx_auth_token_expires ON auth_token (tenant_id, expires_at);

CREATE TABLE kyc_document (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    user_id UUID NOT NULL REFERENCES users(id),
    document_type VARCHAR(50) NOT NULL,
    document_number VARCHAR(100) NOT NULL,
    document_url VARCHAR(2000),
    verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    rejection_reason VARCHAR(500),
    verified_at TIMESTAMP,
    verified_by UUID REFERENCES users(id),
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_kyc_document_tenant ON kyc_document (tenant_id);
CREATE INDEX idx_kyc_document_user ON kyc_document (tenant_id, user_id);
CREATE INDEX idx_kyc_document_status ON kyc_document (tenant_id, verification_status);

CREATE TABLE move_record (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    unit_id UUID NOT NULL REFERENCES unit(id),
    user_id UUID NOT NULL REFERENCES users(id),
    move_type VARCHAR(20) NOT NULL,
    effective_date DATE NOT NULL,
    security_deposit NUMERIC(12, 2),
    agreement_url VARCHAR(2000),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    decision_notes VARCHAR(500),
    approved_by UUID REFERENCES users(id),
    approval_date DATE,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_move_record_tenant ON move_record (tenant_id);
CREATE INDEX idx_move_record_unit ON move_record (tenant_id, unit_id);
CREATE INDEX idx_move_record_status ON move_record (tenant_id, status);

CREATE TABLE parking_slot (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    slot_number VARCHAR(50) NOT NULL UNIQUE,
    parking_type VARCHAR(50) NOT NULL,
    vehicle_type VARCHAR(50) NOT NULL,
    unit_id UUID REFERENCES unit(id),
    allocated BOOLEAN NOT NULL DEFAULT FALSE,
    allocated_at TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_parking_slot_tenant ON parking_slot (tenant_id);
CREATE INDEX idx_parking_slot_allocated ON parking_slot (tenant_id, allocated);
CREATE INDEX idx_parking_slot_unit ON parking_slot (tenant_id, unit_id);

CREATE TABLE digital_id_card (
    tenant_id UUID NOT NULL REFERENCES tenant (id),
    user_id UUID NOT NULL REFERENCES users(id),
    qr_code_data VARCHAR(1000) NOT NULL UNIQUE,
    qr_code_url VARCHAR(2000),
    issue_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deactivated_at TIMESTAMP,
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_digital_id_card_tenant ON digital_id_card (tenant_id);
CREATE INDEX idx_digital_id_card_user ON digital_id_card (tenant_id, user_id);
CREATE INDEX idx_digital_id_card_active ON digital_id_card (tenant_id, active);
